# Generated by Django 5.0.3 on 2024-07-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Subject', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=1000)),
                ('Topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_App.topic')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Content', models.CharField(max_length=1000)),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_App.post')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend_App.user')),
            ],
        ),
    ]
