# Generated by Django 5.0.3 on 2024-08-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='User_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
