# Generated by Django 5.0.3 on 2024-10-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0005_rename_post_id_answer_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Voting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
