# Generated by Django 5.0.3 on 2024-10-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0006_post_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Voting',
            field=models.IntegerField(default=0),
        ),
    ]
