# Generated by Django 5.0.3 on 2024-10-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='disliked_posts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_posts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disliked_posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disliked_posts', to='Backend_App.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='Backend_App.post'),
            preserve_default=False,
        ),
    ]
