# Generated by Django 5.0.3 on 2024-10-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0009_remove_userprofile_disliked_posts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
