# Generated by Django 5.0.3 on 2024-10-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0011_post_disliked_by_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Voting',
        ),
    ]
