# Generated by Django 5.0.3 on 2024-10-08 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0012_remove_post_voting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
