# Generated by Django 5.0.3 on 2024-10-09 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0013_answer_disliked_by_answer_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='avatars/')),
                ('users', models.ManyToManyField(blank=True, related_name='avatars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
