# Generated by Django 5.0.3 on 2024-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0016_alter_answer_content_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
