# Generated by Django 5.0.3 on 2024-11-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0018_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.CharField(),
        ),
    ]
