# Generated by Django 5.0.3 on 2024-11-29 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0019_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('Users', models.ManyToManyField(blank=True, related_name='CatImage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
