version: '3.8'

services:
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'archery-forum-db'
      POSTGRES_USER: 'noa'
      POSTGRES_PASSWORD: 'new_password'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
