FROM node:22.11.0 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npx ngcc --properties es2024 browser module main --first-only --create-ivy-entry-points

COPY ./src ./src
COPY ./public ./
COPY angular.json tsconfig.json tsconfig.app.json ./


RUN npm run build

FROM nginx
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/archery-forum/browser ./
COPY /public ./

EXPOSE 80
