services:
  archery-forum:
    container_name: frontend
    build: .
    image: archery-forum
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./public:/usr/share/nginx/html/public

# very important: add <try_files $uri /index.html;> to locations config in etc/ngnix/conf.d/conf.d file
